baseURL = "https://ogrodnikprojektuje.pl/blog/"
languageCode = "pl-PL"
title = "Blog – ogrodnik projektuje"
publishDir = "../blog"

[params]
  mainSiteURL = "/"
  description = "Porady ogrodnicze, inspiracje i aktualności z pracowni ogrodnikprojektuje.pl"

[taxonomies]
  tag = "tags"
