name: Upload resources

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # normalize all JPG related files (eg. .JPEG, .JPG, .jpg) to .jpg
    - name: Normalize JPG files
      run: |
        for file in resources/*; do
          if [[ -f "$file" ]]; then
            extension="${file##*.}"
            if [[ "$extension" =~ ^(jpg|jpeg|JPG|JPEG)$ ]]; then
              base="${file%.*}"
              mv "$file" "${base}.jpg"
            fi
          fi
        done

    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload *.jpg files
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name mamastronahoststorage --pattern "*.jpg" --auth-mode key -d '$web' -s resources --destination-path resources --overwrite --content-type "image/jpeg"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
